import { defineConfig } from "tsup"

const components = [
  "accordion",
  "alert",
  "alert-dialog",
  "aspect-ratio",
  "avatar",
  "badge",
  "breadcrumb",
  "button",
  "button-group",
  "calendar",
  "carousel",
  "card",
  "chart",
  "checkbox",
  "collapsible",
  "command",
  "command-palette",
  "confirm-dialog",
  "context-menu",
  "data-table",
  "dialog",
  "direction",
  "dropdown-menu",
  "drawer",
  "empty",
  "field",
  "form-field",
  "hover-card",
  "input",
  "item",
  "input-group",
  "input-otp",
  "kbd",
  "label",
  "menubar",
  "multi-select",
  "native-select",
  "navigation-menu",
  "pagination",
  "popover",
  "progress",
  "radio-group",
  "resizable",
  "scroll-area",
  "select",
  "sidebar",
  "separator",
  "sheet",
  "skeleton",
  "slider",
  "sonner",
  "spinner",
  "switch",
  "table",
  "tabs",
  "textarea",
  "toggle",
  "toggle-group",
  "tooltip",
]

const external = [
  "react",
  "react-dom",
  "tailwindcss",
  "radix-ui",
  "lucide-react",
  "vaul",
  "cmdk",
  "input-otp",
  "embla-carousel-react",
  "sonner",
  "react-day-picker",
  "recharts",
  "react-resizable-panels",
  "class-variance-authority",
  "clsx",
  "tailwind-merge",
]

export default defineConfig([
  {
    entry: ["src/index.ts"],
    format: ["esm", "cjs"],
    dts: true,
    clean: true,
    sourcemap: true,
    external,
  },
  ...components.map((name) => ({
    entry: [`src/${name}/index.tsx`],
    format: ["esm", "cjs"] as const,
    dts: true,
    clean: false,
    sourcemap: true,
    external,
    outDir: `dist/${name}`,
  })),
])
